name: Deploy to Fly.io

on:
  push:
    branches: [ "main" ]

env:
  FLY_APP: "meu-agente-seu-sufixo"   # == app do fly.toml
  FLY_REGION: "gru"                  # São Paulo
  OPENAI_MODEL: "gpt-4o-mini"
  EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  DATA_DIR: "/app/data"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Ensure app exists
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl apps create "$FLY_APP" --region "$FLY_REGION" || echo "App já existe"

      - name: Set Fly secrets (LLM keys)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # só seta se existir no GitHub Secrets
          [ -n "$OPENAI_API_KEY" ] && flyctl secrets set OPENAI_API_KEY="$OPENAI_API_KEY" --app "$FLY_APP" || true
          [ -n "$GEMINI_API_KEY" ] && flyctl secrets set GEMINI_API_KEY="$GEMINI_API_KEY" --app "$FLY_APP" || true
          flyctl secrets set OPENAI_MODEL="$OPENAI_MODEL" EMBEDDING_MODEL="$EMBEDDING_MODEL" DATA_DIR="$DATA_DIR" --app "$FLY_APP"

      - name: Deploy (remote builder)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only --app "$FLY_APP" --region "$FLY_REGION"
